/* Source and licensing information for the line(s) below can be found at https://service-lux.by/modules/contrib/webform/js/webform.dialog.js. */
(function($,Drupal,drupalSettings){'use strict';Drupal.webform=Drupal.webform||{};Drupal.webform.dialog=Drupal.webform.dialog||{};Drupal.webform.dialog.options=Drupal.webform.dialog.options||{};Drupal.webformOpenDialog=function(url,type){var $div=$('<div><a href="'+url+'" class="webform-dialog '+type+'"></a></div>');Drupal.behaviors.webformDialog.attach($div);$div.find('a').trigger('click')};Drupal.behaviors.webformDialog={attach:function(context){$('a.webform-dialog',context).once('webform-dialog').each(function(){var $a=$(this),options=$.extend({},Drupal.webform.dialog.options);if($a.attr('class').match(/webform-dialog-([a-z0-9_]+)/)){var dialogOptionsName=RegExp.$1;if(drupalSettings.webform.dialog.options[dialogOptionsName]){options=drupalSettings.webform.dialog.options[dialogOptionsName];delete options.title}};if($(this).data('dialog-options'))$.extend(options,$(this).data('dialog-options'));var href=$a.attr('href');if(href.indexOf('?source_entity_type=ENTITY_TYPE&source_entity_id=ENTITY_ID')!==-1){if(drupalSettings.webform.dialog.entity_type&&drupalSettings.webform.dialog.entity_id){href=href.replace('ENTITY_TYPE',encodeURIComponent(drupalSettings.webform.dialog.entity_type));href=href.replace('ENTITY_ID',encodeURIComponent(drupalSettings.webform.dialog.entity_id))}else href=href.replace('?source_entity_type=ENTITY_TYPE&source_entity_id=ENTITY_ID','');$a.attr('href',href)};href+=(href.indexOf('?')===-1?'?':'&')+'_webform_dialog=1';var element_settings={};element_settings.progress={type:'fullscreen'};element_settings.url=href;element_settings.event='click';element_settings.dialogType=$a.data('dialog-type')||'modal';element_settings.dialog=options;element_settings.element=this;element_settings.error=function error(xmlhttp,uri){if(xmlhttp.status===403)window.location.replace(href.split('?')[0])};Drupal.ajax(element_settings)})}}})(jQuery,Drupal,drupalSettings)
/* Source and licensing information for the above line(s) can be found at https://service-lux.by/modules/contrib/webform/js/webform.dialog.js. */;
/* Source and licensing information for the line(s) below can be found at https://service-lux.by/themes/custom/allsbpr5/src/js/hiddenblock.js. */
(function($){$(".img").hover(function(){$(".imgv").addClass("block-hiden")},function(){$(".imgv").removeClass("block-hiden")})})(jQuery)
/* Source and licensing information for the above line(s) can be found at https://service-lux.by/themes/custom/allsbpr5/src/js/hiddenblock.js. */;
/* Source and licensing information for the line(s) below can be found at https://service-lux.by/themes/custom/allsbpr5/src/js/landing.scroll.js. */
(function($){jQuery(window).scroll(function(){var $sections=$('section');$sections.each(function(i,el){var top=$(el).offset().top-40,bottom=top+$(el).height(),scroll=$(window).scrollTop(),id=$(el).attr('id');if(scroll>top&&scroll<bottom){$('a.active').removeClass('active');$('a[href="#'+id+'"]').addClass('active')}})})})(jQuery);(function($){$('a[href*="#"]').on('click',function(){$('html, body').animate({scrollTop:$($.attr(this,'href')).offset().top-200},400);return false})})(jQuery)
/* Source and licensing information for the above line(s) can be found at https://service-lux.by/themes/custom/allsbpr5/src/js/landing.scroll.js. */;
/* Source and licensing information for the line(s) below can be found at https://service-lux.by/core/misc/form.js. */
(function($,Drupal,debounce){$.fn.drupalGetSummary=function(){var callback=this.data('summaryCallback');return this[0]&&callback?callback(this[0]).trim():''};$.fn.drupalSetSummary=function(callback){var self=this;if(typeof callback!=='function'){var val=callback;callback=function callback(){return val}};return this.data('summaryCallback',callback).off('formUpdated.summary').on('formUpdated.summary',function(){self.trigger('summaryUpdated')}).trigger('summaryUpdated')};Drupal.behaviors.formSingleSubmit={attach:function attach(){function onFormSubmit(e){var $form=$(e.currentTarget),formValues=$form.serialize(),previousValues=$form.attr('data-drupal-form-submit-last');if(previousValues===formValues){e.preventDefault()}else $form.attr('data-drupal-form-submit-last',formValues)};$(once('form-single-submit','body')).on('submit.singleSubmit','form:not([method~="GET"])',onFormSubmit)}}
function triggerFormUpdated(element){$(element).trigger('formUpdated')}
function fieldsList(form){return[].map.call(form.querySelectorAll('[name][id]'),function(el){return el.id})};Drupal.behaviors.formUpdated={attach:function attach(context){var $context=$(context),contextIsForm=$context.is('form'),$forms=$(once('form-updated',contextIsForm?$context:$context.find('form'))),formFields;if($forms.length)$.makeArray($forms).forEach(function(form){var events='change.formUpdated input.formUpdated ',eventHandler=debounce(function(event){triggerFormUpdated(event.target)},300);formFields=fieldsList(form).join(',');form.setAttribute('data-drupal-form-fields',formFields);$(form).on(events,eventHandler)});if(contextIsForm){formFields=fieldsList(context).join(',');var currentFields=$(context).attr('data-drupal-form-fields');if(formFields!==currentFields)triggerFormUpdated(context)}},detach:function detach(context,settings,trigger){var $context=$(context),contextIsForm=$context.is('form');if(trigger==='unload')once.remove('form-updated',contextIsForm?$context:$context.find('form')).forEach(function(form){form.removeAttribute('data-drupal-form-fields');$(form).off('.formUpdated')})}};Drupal.behaviors.fillUserInfoFromBrowser={attach:function attach(context,settings){var userInfo=['name','mail','homepage'],$forms=$(once('user-info-from-browser','[data-user-info-from-browser]'));if($forms.length)userInfo.forEach(function(info){var $element=$forms.find("[name=".concat(info,"]")),browserData=localStorage.getItem("Drupal.visitor.".concat(info));if(!$element.length)return;var emptyValue=$element[0].value==='',defaultValue=$element.attr('data-drupal-default-value')===$element[0].value;if(browserData&&(emptyValue||defaultValue))$element.each(function(index,item){item.value=browserData})});$forms.on('submit',function(){userInfo.forEach(function(info){var $element=$forms.find("[name=".concat(info,"]"));if($element.length)localStorage.setItem("Drupal.visitor.".concat(info),$element[0].value)})})}};var handleFragmentLinkClickOrHashChange=function handleFragmentLinkClickOrHashChange(e){var url;if(e.type==='click'){url=e.currentTarget.location?e.currentTarget.location:e.currentTarget}else url=window.location;var hash=url.hash.substr(1);if(hash){var $target=$("#".concat(hash));$('body').trigger('formFragmentLinkClickOrHashChange',[$target]);setTimeout(function(){return $target.trigger('focus')},300)}},debouncedHandleFragmentLinkClickOrHashChange=debounce(handleFragmentLinkClickOrHashChange,300,true);$(window).on('hashchange.form-fragment',debouncedHandleFragmentLinkClickOrHashChange);$(document).on('click.form-fragment','a[href*="#"]',debouncedHandleFragmentLinkClickOrHashChange)})(jQuery,Drupal,Drupal.debounce)
/* Source and licensing information for the above line(s) can be found at https://service-lux.by/core/misc/form.js. */;
/* Source and licensing information for the line(s) below can be found at https://service-lux.by/modules/contrib/webform/js/webform.behaviors.js. */
(function($,Drupal){'use strict';var isChrome=(/chrom(e|ium)/.test(window.navigator.userAgent.toLowerCase()));if(isChrome){var backButton=false;if(window.performance){var navEntries=window.performance.getEntriesByType('navigation');if(navEntries.length>0&&navEntries[0].type==='back_forward'){backButton=true}else if(window.performance.navigation&&window.performance.navigation.type===window.performance.navigation.TYPE_BACK_FORWARD)backButton=true};if(backButton){var attachBehaviors=Drupal.attachBehaviors;Drupal.attachBehaviors=function(context,settings){setTimeout(function(context,settings){attachBehaviors(context,settings)},300)}}}})(jQuery,Drupal)
/* Source and licensing information for the above line(s) can be found at https://service-lux.by/modules/contrib/webform/js/webform.behaviors.js. */;
