/* Source and licensing information for the line(s) below can be found at https://service-lux.by/core/assets/vendor/jquery.ui/ui/version-min.js. */
!function(e){"use strict";"function"==typeof define&&define.amd?define(["jquery"],e):e(jQuery)}((function(e){"use strict";return e.ui=e.ui||{},e.ui.version="1.13.2"}))
/* Source and licensing information for the above line(s) can be found at https://service-lux.by/core/assets/vendor/jquery.ui/ui/version-min.js. */;
/* Source and licensing information for the line(s) below can be found at https://service-lux.by/core/assets/vendor/jquery.ui/ui/data-min.js. */
!function(e){"use strict";"function"==typeof define&&define.amd?define(["jquery","./version"],e):e(jQuery)}((function(e){"use strict";return e.extend(e.expr.pseudos,{data:e.expr.createPseudo?e.expr.createPseudo((function(n){return function(t){return!!e.data(t,n)}})):function(n,t,r){return!!e.data(n,r[3])}})}))
/* Source and licensing information for the above line(s) can be found at https://service-lux.by/core/assets/vendor/jquery.ui/ui/data-min.js. */;
/* Source and licensing information for the line(s) below can be found at https://service-lux.by/core/assets/vendor/jquery.ui/ui/disable-selection-min.js. */
!function(e){"use strict";"function"==typeof define&&define.amd?define(["jquery","./version"],e):e(jQuery)}((function(e){"use strict";return e.fn.extend({disableSelection:(n="onselectstart"in document.createElement("div")?"selectstart":"mousedown",function(){return this.on(n+".ui-disableSelection",(function(e){e.preventDefault()}))}),enableSelection:function(){return this.off(".ui-disableSelection")}});var n}))
/* Source and licensing information for the above line(s) can be found at https://service-lux.by/core/assets/vendor/jquery.ui/ui/disable-selection-min.js. */;
/* Source and licensing information for the line(s) below can be found at https://service-lux.by/core/assets/vendor/jquery.ui/ui/focusable-min.js. */
!function(e){"use strict";"function"==typeof define&&define.amd?define(["jquery","./version"],e):e(jQuery)}((function(e){"use strict";return e.ui.focusable=function(i,t){var n,s,r,u,a,o=i.nodeName.toLowerCase();return"area"===o?(s=(n=i.parentNode).name,!(!i.href||!s||"map"!==n.nodeName.toLowerCase())&&((r=e("img[usemap='#"+s+"']")).length>0&&r.is(":visible"))):(/^(input|select|textarea|button|object)$/.test(o)?(u=!i.disabled)&&(a=e(i).closest("fieldset")[0])&&(u=!a.disabled):u="a"===o&&i.href||t,u&&e(i).is(":visible")&&function(e){var i=e.css("visibility");for(;"inherit"===i;)i=(e=e.parent()).css("visibility");return"visible"===i}(e(i)))},e.extend(e.expr.pseudos,{focusable:function(i){return e.ui.focusable(i,null!=e.attr(i,"tabindex"))}}),e.ui.focusable}))
/* Source and licensing information for the above line(s) can be found at https://service-lux.by/core/assets/vendor/jquery.ui/ui/focusable-min.js. */;
/* Source and licensing information for the line(s) below can be found at https://service-lux.by/core/assets/vendor/jquery.ui/ui/form-min.js. */
!function(t){"use strict";"function"==typeof define&&define.amd?define(["jquery","./version"],t):t(jQuery)}((function(t){"use strict";return t.fn._form=function(){return"string"==typeof this[0].form?this.closest("form"):t(this[0].form)}}))
/* Source and licensing information for the above line(s) can be found at https://service-lux.by/core/assets/vendor/jquery.ui/ui/form-min.js. */;
/* Source and licensing information for the line(s) below can be found at https://service-lux.by/core/assets/vendor/jquery.ui/ui/ie-min.js. */
!function(e){"use strict";"function"==typeof define&&define.amd?define(["jquery","./version"],e):e(jQuery)}((function(e){"use strict";return e.ui.ie=!!/msie [\w.]+/.exec(navigator.userAgent.toLowerCase())}))
/* Source and licensing information for the above line(s) can be found at https://service-lux.by/core/assets/vendor/jquery.ui/ui/ie-min.js. */;
/* Source and licensing information for the line(s) below can be found at https://service-lux.by/core/assets/vendor/jquery.ui/ui/jquery-patch-min.js. */
!function(e){"use strict";"function"==typeof define&&define.amd?define(["jquery","./version"],e):e(jQuery)}((function(e){"use strict";if(e.expr.pseudos||(e.expr.pseudos=e.expr[":"]),e.uniqueSort||(e.uniqueSort=e.unique),!e.escapeSelector){var n=/([\0-\x1f\x7f]|^-?\d)|^-$|[^\x80-\uFFFF\w-]/g,t=function(e,n){return n?"\0"===e?"�":e.slice(0,-1)+"\\"+e.charCodeAt(e.length-1).toString(16)+" ":"\\"+e};e.escapeSelector=function(e){return(e+"").replace(n,t)}};e.fn.even&&e.fn.odd||e.fn.extend({even:function(){return this.filter((function(e){return e%2==0}))},odd:function(){return this.filter((function(e){return e%2==1}))}})}))
/* Source and licensing information for the above line(s) can be found at https://service-lux.by/core/assets/vendor/jquery.ui/ui/jquery-patch-min.js. */;
