/* Source and licensing information for the line(s) below can be found at https://service-lux.by/core/assets/vendor/ckeditor5/ckeditor5-dll/translations/ru.js. */
!function(e){const t=e.ru=e.ru||{};t.dictionary=Object.assign(t.dictionary||{},{"%0 of %1":"%0 из %1",Aquamarine:"Аквамариновый",Black:"Чёрный",Blue:"Синий",Cancel:"Отмена","Cannot upload file:":"Невозможно загрузить файл","Dim grey":"Тёмно-серый","Dropdown toolbar":"Выпадающая панель инструментов","Edit block":"Редактировать блок","Editor block content toolbar":"Панель инструментов редактора","Editor contextual toolbar":"Контекстуальная панель инструментов редактора","Editor editing area: %0":"Область редактирования редактора: %0","Editor toolbar":"Панель инструментов редактора",Green:"Зелёный",Grey:"Серый","Insert paragraph after block":"Вставить параграф после блока","Insert paragraph before block":"Вставить параграф перед блоком","Light blue":"Голубой","Light green":"Салатовый","Light grey":"Светло-серый",Next:"Следующий",Orange:"Оранжевый","Press Enter to type after or press Shift + Enter to type before the widget":"Нажмите Enter для ввода текста после виджета или нажмите Shift + Enter для ввода текста перед виджетом",Previous:"Предыдущий",Purple:"Фиолетовый",Red:"Красный",Redo:"Повторить","Remove color":"Убрать цвет","Restore default":"По умолчанию","Rich Text Editor":"Редактор","Rich Text Editor. Editing area: %0":"Редактор форматированного текста. Область редактирования: %0",Save:"Сохранить","Select all":"Выбрать все","Show more items":"Другие инструменты",Turquoise:"Бирюзовый",Undo:"Отменить","Upload in progress":"Идёт загрузка",White:"Белый","Widget toolbar":"Панель инструментов виджета",Yellow:"Жёлтый"}),t.getPluralForm=function(e){return e%10==1&&e%100!=11?0:e%10>=2&&e%10<=4&&(e%100<12||e%100>14)?1:e%10==0||e%10>=5&&e%10<=9||e%100>=11&&e%100<=14?2:3}}(window.CKEDITOR_TRANSLATIONS||(window.CKEDITOR_TRANSLATIONS={}));
/* Source and licensing information for the above line(s) can be found at https://service-lux.by/core/assets/vendor/ckeditor5/ckeditor5-dll/translations/ru.js. */;
/* Source and licensing information for the line(s) below can be found at https://service-lux.by/core/assets/vendor/ckeditor5/html-support/translations/ru.js. */
!function(i){const n=i.ru=i.ru||{};n.dictionary=Object.assign(n.dictionary||{},{"HTML object":"HTML объект"})}(window.CKEDITOR_TRANSLATIONS||(window.CKEDITOR_TRANSLATIONS={}));
/* Source and licensing information for the above line(s) can be found at https://service-lux.by/core/assets/vendor/ckeditor5/html-support/translations/ru.js. */;
/* Source and licensing information for the line(s) below can be found at https://service-lux.by/core/assets/vendor/ckeditor5/basic-styles/translations/ru.js. */
!function(i){const n=i.ru=i.ru||{};n.dictionary=Object.assign(n.dictionary||{},{Bold:"Жирный",Code:"Исходный код",Italic:"Курсив",Strikethrough:"Зачеркнутый",Subscript:"Подстрочный",Superscript:"Надстрочный",Underline:"Подчеркнутый"})}(window.CKEDITOR_TRANSLATIONS||(window.CKEDITOR_TRANSLATIONS={}));
/* Source and licensing information for the above line(s) can be found at https://service-lux.by/core/assets/vendor/ckeditor5/basic-styles/translations/ru.js. */;
/* Source and licensing information for the line(s) below can be found at https://service-lux.by/core/assets/vendor/ckeditor5/heading/translations/ru.js. */
!function(n){const e=n.ru=n.ru||{};e.dictionary=Object.assign(e.dictionary||{},{"Choose heading":"Выбор стиля",Heading:"Стиль","Heading 1":"Заголовок 1","Heading 2":"Заголовок 2","Heading 3":"Заголовок 3","Heading 4":"Заголовок 4","Heading 5":"Заголовок 5","Heading 6":"Заголовок 6",Paragraph:"Параграф","Type or paste your content here.":"Введите или вставьте сюда ваш текст","Type your title":"Введите заголовок"})}(window.CKEDITOR_TRANSLATIONS||(window.CKEDITOR_TRANSLATIONS={}));
/* Source and licensing information for the above line(s) can be found at https://service-lux.by/core/assets/vendor/ckeditor5/heading/translations/ru.js. */;
/* Source and licensing information for the line(s) below can be found at https://service-lux.by/core/assets/vendor/ckeditor5/image/translations/ru.js. */
!function(e){const i=e.ru=e.ru||{};i.dictionary=Object.assign(i.dictionary||{},{"Break text":"Разрывать текст","Caption for image: %0":"Подпись к изображению: %0","Caption for the image":"Подпись к изображению","Centered image":"Выравнивание по центру","Change image text alternative":"Редактировать альтернативный текст","Enter image caption":"Подпись к изображению","Full size image":"Оригинальный размер изображения","Image resize list":"Список размеров","Image toolbar":"Панель инструментов изображения","image widget":"Виджет изображений","In line":"В тексте",Insert:"Вставить","Insert image":"Вставить изображение","Insert image via URL":"Вставить изображение по URL","Left aligned image":"Выравнивание по левому краю",Original:"Оригинальный","Resize image":"Изменить размер изображения","Resize image to %0":"Изменить размер изображения до %0","Resize image to the original size":"Вернуть размер изображения к оригинальному","Right aligned image":"Выравнивание по правому краю","Side image":"Боковое изображение","Text alternative":"Альтернативный текст",Update:"Изменить","Update image URL":"Изменить URL изображения","Upload failed":"Загрузка не выполнена","Wrap text":"Обтекать текст"})}(window.CKEDITOR_TRANSLATIONS||(window.CKEDITOR_TRANSLATIONS={}));
/* Source and licensing information for the above line(s) can be found at https://service-lux.by/core/assets/vendor/ckeditor5/image/translations/ru.js. */;
/* Source and licensing information for the line(s) below can be found at https://service-lux.by/core/assets/vendor/ckeditor5/block-quote/translations/ru.js. */
!function(i){const n=i.ru=i.ru||{};n.dictionary=Object.assign(n.dictionary||{},{"Block quote":"Цитата"})}(window.CKEDITOR_TRANSLATIONS||(window.CKEDITOR_TRANSLATIONS={}));
/* Source and licensing information for the above line(s) can be found at https://service-lux.by/core/assets/vendor/ckeditor5/block-quote/translations/ru.js. */;
/* Source and licensing information for the line(s) below can be found at https://service-lux.by/core/assets/vendor/ckeditor5/link/translations/ru.js. */
!function(n){const i=n.ru=n.ru||{};i.dictionary=Object.assign(i.dictionary||{},{Downloadable:"Загружаемые","Edit link":"Редактировать ссылку",Link:"Ссылка","Link image":"Ссылка на изображение","Link URL":"Ссылка URL","Open in a new tab":"Открыть в новой вкладке","Open link in new tab":"Открыть ссылку в новой вкладке","This link has no URL":"Для этой ссылки не установлен адрес URL",Unlink:"Убрать ссылку"})}(window.CKEDITOR_TRANSLATIONS||(window.CKEDITOR_TRANSLATIONS={}));
/* Source and licensing information for the above line(s) can be found at https://service-lux.by/core/assets/vendor/ckeditor5/link/translations/ru.js. */;
/* Source and licensing information for the line(s) below can be found at https://service-lux.by/core/assets/vendor/ckeditor5/list/translations/ru.js. */
!function(e){const t=e.ru=e.ru||{};t.dictionary=Object.assign(t.dictionary||{},{"Bulleted List":"Маркированный список","Bulleted list styles toolbar":"Стили маркированного списка",Circle:"Окружность",Decimal:"Десятичный","Decimal with leading zero":"Десятичный с ведущим нулем",Disc:"Диск","List properties":"Свойства списка","Lower-latin":"Малые латинские","Lower–roman":"Малые римские","Numbered List":"Нумерованный список","Numbered list styles toolbar":"Стили нумерованного списка","Reversed order":"Обратный порядок",Square:"Квадрат","Start at":"Начать с","Start index must be greater than 0.":"Начальный индекс должен быть больше 0.","To-do List":"Список задач","Toggle the circle list style":"Переключить на стиль списка с маркерами в виде незакрашенного кружка","Toggle the decimal list style":"Переключить на стиль списка с цифровыми маркерами","Toggle the decimal with leading zero list style":"Переключить на стиль списка с маркерами в виде цифр с нулем в начале","Toggle the disc list style":"Переключить на стиль списка с маркерами в виде закрашенного кружка","Toggle the lower–latin list style":"Переключить на стиль списка с маркерами в виде строчных латинских букв","Toggle the lower–roman list style":"Переключить на стиль списка с маркерами в виде строчных римских цифр","Toggle the square list style":"Переключить на стиль списка с квадратными маркерами","Toggle the upper–latin list style":"Переключить на стиль списка с маркерами в виде заглавных латинских букв","Toggle the upper–roman list style":"Переключить на стиль списка с маркерами в виде заглавных римских цифр","Upper-latin":"Большие латинские","Upper-roman":"Большие римские"})}(window.CKEDITOR_TRANSLATIONS||(window.CKEDITOR_TRANSLATIONS={}));
/* Source and licensing information for the above line(s) can be found at https://service-lux.by/core/assets/vendor/ckeditor5/list/translations/ru.js. */;
