/* Source and licensing information for the line(s) below can be found at https://service-lux.by/modules/contrib/clientside_validation/clientside_validation_jquery/js/cv.jquery.validate.js. */
(function($,Drupal,drupalSettings){'use strict';if(typeof drupalSettings.cvJqueryValidateOptions==='undefined')drupalSettings.cvJqueryValidateOptions={};if(drupalSettings.clientside_validation_jquery.force_validate_on_blur)drupalSettings.cvJqueryValidateOptions.onfocusout=function(element){this.element(element)};$.extend($.validator.messages,drupalSettings.clientside_validation_jquery.messages);Drupal.behaviors.cvJqueryValidate={attach:function(context){if(typeof Drupal.Ajax!=='undefined')if(typeof Drupal.Ajax.prototype.beforeSubmitCVOriginal==='undefined'){var validateAll=2;try{validateAll=drupalSettings.clientside_validation_jquery.validate_all_ajax_forms}catch(e){};Drupal.Ajax.prototype.beforeSubmitCVOriginal=Drupal.Ajax.prototype.beforeSubmit;Drupal.Ajax.prototype.beforeSubmit=function(form_values,element_settings,options){if(typeof this.$form!=='undefined'&&(validateAll===1||$(this.element).hasClass('cv-validate-before-ajax'))&&$(this.element).attr("formnovalidate")==undefined){$(this.$form).removeClass('ajax-submit-prevented');$(this.$form).validate();if(!($(this.$form).valid())){this.ajaxing=false;$(this.$form).addClass('ajax-submit-prevented');return false}};return this.beforeSubmitCVOriginal.apply(this,arguments)}};$(document).trigger('cv-jquery-validate-options-update',drupalSettings.cvJqueryValidateOptions);$('body').find('form').once('cvJqueryValidate').each(function(){$(this).validate(drupalSettings.cvJqueryValidateOptions)})}}})(jQuery,Drupal,drupalSettings)
/* Source and licensing information for the above line(s) can be found at https://service-lux.by/modules/contrib/clientside_validation/clientside_validation_jquery/js/cv.jquery.validate.js. */;
/* Source and licensing information for the line(s) below can be found at https://service-lux.by/modules/contrib/clientside_validation/clientside_validation_jquery/js/cv.jquery.ckeditor.js. */
(function($,Drupal,debounce,CKEDITOR){Drupal.behaviors.cvJqueryValidateCKEditor={attach:function(context){if(typeof CKEDITOR==='undefined')return;var ignore=':hidden',not=[];for(var instance in CKEDITOR.instances)if(CKEDITOR.instances.hasOwnProperty(instance))not.push('#'+instance);ignore+=not.length?':not('+not.join(', ')+')':'';$('form').each(function(){var validator=$(this).data('validator');if(!validator)return;validator.settings.ignore=ignore;validator.settings.errorPlacement=function(place,$element){var id=$element.attr('id'),afterElement=$element[0];if(CKEDITOR.instances.hasOwnProperty(id))afterElement=CKEDITOR.instances[id].container.$;place.insertAfter(afterElement)}});var updateText=function(instance){return debounce(function(e){instance.updateElement();var event=$.extend(true,{},e.data.$);delete event.target;delete event.explicitOriginalTarget;delete event.originalTarget;delete event.currentTarget;$(instance.element.$).trigger(new $.Event(e.name,event))},250)};CKEDITOR.on('instanceReady',function(){for(var instance in CKEDITOR.instances)if(CKEDITOR.instances.hasOwnProperty(instance)){CKEDITOR.instances[instance].document.on("keyup",updateText(CKEDITOR.instances[instance]));CKEDITOR.instances[instance].document.on("paste",updateText(CKEDITOR.instances[instance]));CKEDITOR.instances[instance].document.on("keypress",updateText(CKEDITOR.instances[instance]));CKEDITOR.instances[instance].document.on("blur",updateText(CKEDITOR.instances[instance]));CKEDITOR.instances[instance].document.on("change",updateText(CKEDITOR.instances[instance]))}})}}})(jQuery,Drupal,Drupal.debounce,(typeof CKEDITOR==='undefined')?undefined:CKEDITOR)
/* Source and licensing information for the above line(s) can be found at https://service-lux.by/modules/contrib/clientside_validation/clientside_validation_jquery/js/cv.jquery.ckeditor.js. */;
/* Source and licensing information for the line(s) below can be found at https://service-lux.by/modules/contrib/better_exposed_filters/js/better_exposed_filters.js. */
(function($,Drupal,drupalSettings){Drupal.behaviors.betterExposedFilters={attach:function(context,settings){$('.bef-tree input[type=checkbox], .bef-checkboxes input[type=checkbox]').change(function(){_bef_highlight(this,context)}).filter(':checked').closest('.form-item',context).addClass('highlight')}}
function _bef_highlight(elem,context){$elem=$(elem,context);$elem.attr('checked')?$elem.closest('.form-item',context).addClass('highlight'):$elem.closest('.form-item',context).removeClass('highlight')}})(jQuery,Drupal,drupalSettings)
/* Source and licensing information for the above line(s) can be found at https://service-lux.by/modules/contrib/better_exposed_filters/js/better_exposed_filters.js. */;
/* Source and licensing information for the line(s) below can be found at https://service-lux.by/modules/contrib/better_exposed_filters/js/auto_submit.js. */
(function($,Drupal,once){Drupal.behaviors.betterExposedFiltersAutoSubmit={attach:function(context){var selectors='form[data-bef-auto-submit-full-form], [data-bef-auto-submit-full-form] form, [data-bef-auto-submit]';$(selectors,context).addBack(selectors).each(function(i,e){var $form=$(e),autoSubmitDelay=$form.data('bef-auto-submit-delay')||500;$(once('bef-auto-submit',$form)).on('change',triggerSubmit).on('keyup',Drupal.debounce(triggerSubmit,autoSubmitDelay))})
function triggerSubmit(e){var ignoredKeyCodes=[16,17,18,20,33,34,35,36,37,38,39,40,9,13,27],$target=$(e.target),$submit=$target.closest('form').find('[data-bef-auto-submit-click]');if($target.is('[data-bef-auto-submit-exclude], :submit')||($target.attr('autocomplete')=='off'&&!$target.hasClass('bef-datepicker')))return true;if($target.is(':text:not(.hasDatepicker), textarea')&&$.inArray(e.keyCode,ignoredKeyCodes)===-1){$submit.click()}else if(e.type==='change')$submit.click()}}}}(jQuery,Drupal,once))
/* Source and licensing information for the above line(s) can be found at https://service-lux.by/modules/contrib/better_exposed_filters/js/auto_submit.js. */;
